# Generated by Django 5.2.8 on 2025-11-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text="Введите язык книги (например, 'Казалидсткий', 'Квикиш')", max_length=100),
        ),
    ]
